# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'iOS-helloworld-ObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS-helloworld-ObjC
  pod 'SecureElement'
  pod 'MotionDnaSDK'
end
