name: iOS

on: [push, pull_request]

jobs:
  ios-react-native:
    runs-on: macos-latest

    steps:
    - name: Checkout project
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      uses: actions/checkout@v1

    - name: Specify node version
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Detox setup
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Install node_modules & deploy with default XCode version
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      working-directory: ./examples/RNSecureElementTester
      run: |
        yarn install --frozen-lockfile
        yarn detox build -c ios.release.13.1

    - name: iOS test (iOS 13)
      timeout-minutes: 10
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      working-directory: ./examples/RNSecureElementTester
      env:
          DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
      run: |
        sudo xcode-select -s $DEVELOPER_DIR
        yarn detox clean-framework-cache && npx detox build-framework-cache
        yarn detox test -c ios.release.13.1
