name: iOS

on: [push, pull_request]

jobs:
  some-job:
    runs-on: macos-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v1

    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Detox setup
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Install node_modules & deploy with specific XCode version
      working-directory: ./examples/RNSecureElementTester
      env:
          DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
      run: |
        yarn install --frozen-lockfile
        yarn detox build -c ios.release

    - name: iOS test
      working-directory: ./examples/RNSecureElementTester
      run: |
        yarn detox clean-framework-cache && npx detox build-framework-cache
        yarn detox test -c ios.release

    - name: Release new SecureElement version to cocoapods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        COCOA_NAME: ${{ secrets.COCOA_NAME }}
        COCOA_DESCRIPTION: ${{ secrets.COCOA_DESCRIPTION }}
      if: "github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, 'release-ios')"
      run: |
        pod trunk register SecureElement.podspec $COCOA_NAME --description=$COCOA_DESCRIPTION
        pod lib lint SecureElement.podspec --allow-warnings
        pod trunk push SecureElement.podspec --allow-warnings
