name: Native iOS

on: [push, pull_request]

jobs:
  ios-native:
    runs-on: macos-latest

    steps:
    - name: Checkout project
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      uses: actions/checkout@v1

    - name: Deploy
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
      working-directory: ./examples/SecureElementTesterIOS
      run: |
        pod install
        xcodebuild -workspace iOS-helloworld-ObjC.xcworkspace -scheme iOS-helloworld-ObjC -configuration Debug -sdk iphonesimulator
