name: Native Android

on: [push, pull_request]

jobs:
  android-native:
    runs-on: macos-latest

    steps:
    - name: Checkout project
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      uses: actions/checkout@v1

    - name: Use specific Java version
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk8'
        architecture: 'x64'

    - name: Deploy
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      working-directory: ./examples/SecureElementTesterAndroid
      run:
        ./gradlew assembleRelease
